### ISSUE TITLE
how to stop the countdown? seems not work! any example? thanks.

### ISSUE THREAD

**Issue by kingctan** [rendro/countdown#11]
how to stop the countdown? seems not work! any example? thanks.

**Comment by AveVlad** [comment]
lol

**Comment by kelvshi** [comment]
How to remove a countdown? if  I remove the dom where the countdown in,it seems the countdown still work so that the onEnd() method will be trigger.
example:
$('#mydom').countdown({
          date: +(new Date) + 10000,
          onEnd: function() {
            $(this.el).addClass('ended');
          }
    });
$('#mydom').remove();
The onEnd() method still be trigger
