### ISSUE TITLE
[enhancement] Support data attributes

### ISSUE THREAD

**Issue by mickrip** [rendro/countdown#14]
It would be nice to have the facility to set options by using data attributes.

example: 

```
<div class="countdown" data-date="June 7, 2087 15:03:26"></div>
<div class="countdown" data-date="July 9, 2034 13:13:02"></div>

$(".countdown").countdown();
```

**Comment by cmnstmntmn** [comment]
why not using `time` element with `datetime` attribute ?
http://www.w3schools.com/tags/tag_time.asp
