### ISSUE TITLE
Not working on firefox and IE

### ISSUE THREAD

**Issue by snakom23** [rendro/countdown#23]
Not working on firefox and IE.
This is my script:
https://www.mediafire.com/?vbu56612bevf3wb
and added time server zone:
<code>
// End time for diff purposes
        var endTimeDiff = new Date().getTime() + 15000;
        // This is server's time
        var timeThere = new Date();
        // This is client's time (delayed)
        var timeHere = new Date(timeThere.getTime() - 5434);
        // Get the difference between client time and server time
        var diff_ms = timeHere.getTime() - timeThere.getTime();
        // Get the rounded difference in seconds
        var diff_s = diff_ms / 1000 | 0;
        
        var notice = [];
        notice.push('Server time: ' + timeThere.toDateString() + ' ' + timeThere.toTimeString());
        notice.push('Your time: ' + timeHere.toDateString() + ' ' + timeHere.toTimeString());
        notice.push('Time difference: ' + diff_s + ' seconds (' + diff_ms + ' milliseconds to be precise). Your time is a bit behind.');
        
        
        $('.offset-server .countdown').countdown({
          date: endTimeDiff,
          offset: diff_s * 1000,
          onEnd: function() {
            $(this.el).addClass('ended');
          }
        });
</code>
help pls.

**Comment by mk66UK** [comment]
Hi I love you jquery plugin thanks for writing it!

I'm currently having the same issue. It works in Chrome and Safari but not in Firefox and IE. My firebug give me no errors which is strange. Any ideas, I really want to get this working ASAP.

Regards

Mark

**Comment by mk66UK** [comment]
FIXED IT! It was my fault a simple TYPE-O on the date variable. 

The date field format has to be applied in a very precise way! Make sure you set it like the example 

THIS WORK: var endDate = "June 7, 2087 15:03:25";

I had mine like this

DOESN'T WORK: var endDate = "Febuary  01, 2016 00:00:01";

WHAT I DID TO FIX IT: var endDate = "February 1, 2016 0:00:01";

By missing the 'R' out of Feb which made it not work in Firefox and IE. The interesting thing is that Safari and Chrome it still worked (My normal expectation on this type simple human error is, it should break across all browser. I don't understand why it still worked in Safari and Chrome). Any way what important its working now. 

For anyone having the same issue I would advice you to look at this line in the code first to make sure it not you that is at fault.


Regards

Mark
