### ISSUE TITLE
Update method doesn't seem to work

### ISSUE THREAD

**Issue by scazzy** [rendro/countdown#30]
Calling update method, but says 'no such method'

**Comment by rendro** [comment]
Please refer to the [example](https://github.com/rendro/countdown/blob/master/examples/index.html) to see how calling update works. Looks like you are not calling `update` on the countdown instance.

**Comment by scazzy** [comment]
tried all ways, didn't work.
using the minified jquery version. the jquery object didn't have update or any other methods
