### ISSUE TITLE
Doesn't work in Firefox?

### ISSUE THREAD

**Issue by danielbenjamins** [rendro/countdown#34]
In Firefox it says "0 days, 0 hours, 0 minutes and NAN seconds", there's no countdown. In Chrome everything is working fine.

See http://www.concertatsea.nl/

Any suggestions? I don't see any errors in the console.

**Comment by NSDrowned** [comment]
Tested it on my computer. Not working on FF Quantum 58.0.2 (64-bit), but after I updated FF to 59.0.2 it started working.

**Comment by danielbenjamins** [comment]
It seems that Firefox needs a date in English and Chrome doesn't care about that. WordPress inputted a date in Dutch ("juni" instead of "June") and that was working fine in Chrome, but not in Firefox. I changed the date output and it's now working in both Chrome and Firefox.
